---
Name: translatablerouting
After: 'framework/*', 'cms/*', 'translatable/*'
---
MultilingualRootURLController:
    UseLocaleURL: false

SiteTree:
    extensions:
        - 'MultilingualSiteTreeExtension'

Translatable:
    enforce_global_unique_urls: false