---
Name: translatablerouting
After: 'framework/*', 'cms/*', 'translatable/*'
---
SiteTree:
    extensions:
        - 'MultilingualSiteTreeExtension'

Translatable:
    enforce_global_unique_urls: false